### ISSUE TITLE
Create Overview document on how to use STOQS 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [stoqs/stoqs#10]
```
Need an overview document on how to use STOQS: how to form queries, how to use 
graphical front end to navigate available data, how to extract data to feed 
into analysis and visualization tools (such as Matlab)

```

Original issue reported on code.google.com by `du...@mbari.org` on 21 Jun 2012 at 9:58

**Comment by stoqs** [comment]
Also a more general video is at https://www.youtube.com/watch?v=E8wO3qMevV8, a paper at http://dx.doi.org/10.1109/AUV.2014.7054414, and a Wired magazine article at http://www.wired.com/2015/04/robots-roam-earths-imperiled-oceans/.
