### ISSUE TITLE
Install Failure. 

### ISSUE THREAD

**Issue by josephmfaulkner** [stoqs/stoqs#219]
I suppose a bit's changed since the last version of the provision script was written. Following the instructions, when I try to setup a dev environment the script returns with the following error: 

==> default:   Could not find a version that satisfies the requirement scipy==0.17.0 (from -r /home/vagrant/dev/stoqsgit/requirements/development.txt (line 30)) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1)
==> default:   Some externally hosted files were ignored as access to them may be unreliable (use --allow-external scipy to allow).
==> default: No matching distribution found for scipy==0.17.0 (from -r /home/vagrant/dev/stoqsgit/requirements/development.txt (line 30))

**Comment by stoqs** [comment]
Thanks for reporting this issue! https://github.com/stoqs/stoqs/pull/220 should fix it. Please comment whether the install now works or if it doesn't.

**Comment by josephmfaulkner** [comment]
Ok I tried the install again and it looks like we cleared up that issue. Now however, I'm getting the following error: 
default: Command "/home/vagrant/dev/stoqsgit/venv-stoqs/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-vl2R0C/scikit-learn/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ZH5sHh-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/vagrant/dev/stoqsgit/venv-stoqs/include/site/python2.7/scikit-learn" failed with error code 1 in /tmp/pip-build-vl2R0C/scikit-learn

**Comment by MBARIMike** [comment]
scikit-learn requires numpy and scipy to be installed first. https://github.com/MBARIMike/stoqs/commit/f4bc479c6c95e8ddb93bf420f71d356b4cf7e46b puts scipy before scikit-learn. Try doing a 

    git pull
    ./setup.sh

**Comment by stoqs** [comment]
Just checking to see if you are able to get the install to work.

**Comment by josephmfaulkner** [comment]
Apologies for not getting back to you sooner. The installation was successful. I now have the vagrant server up and running. Thank you.
