### ISSUE TITLE
Figure out how to use port 80 on nginx/uwsgi

### ISSUE THREAD

**Issue by MBARIMike** [stoqs/stoqs#233]
It's fairly simple to configure STOQS to run in production following [standard instructions](http://uwsgi-docs.readthedocs.org/en/latest/tutorials/Django_and_nginx.html) using a port such as 8888 (which is the default in the [provided stoqs_nginx.conf](https://github.com/stoqs/stoqs/blob/master/stoqs/stoqs_nginx.conf) file) or 8000 on the current public STOQS server at MBARI: http://stoqs.mbari.org:8000/.

Initial attempts to use port 80 revealed problems that may exist in the [django configuration](https://github.com/stoqs/stoqs/blob/master/stoqs/config/settings/common.py): STATIC_ROOT, STATIC_URL, MEDIA_ROOT, MEDIA_URL settings, etc. These need to be sussed out and fixed.

**Comment by MBARIMike** [comment]
@mcgredonps As we saw yesterday there are also conflicts with the default mapserver running on Apache's port 80. Are there simple proxy pass solutions to this?

**Comment by mcgredonps** [comment]
Yes, you can specify that specific directories not be forwarded on to the
proxy. So for example robodata.ern.nps.edu/mapserv<http://robodata.ern.nps.edu/mapserv> could be excluded
from being forwarded to the back-end django.


On Aug 10, 2016, at 8:09 AM, Mike McCann <notifications@github.com<mailto:notifications@github.com>> wrote:


@mcgredonps<https://github.com/mcgredonps> As we saw yesterday there are also conflicts with the default mapserver running on Apache's port 80. Are there simple proxy pass solutions to this?

**Comment by MBARIMike** [comment]
Port 80 service is now implemented in the Docker-based deployment.
