### ISSUE TITLE
Missing CTD cast / Plankton Pump data for SIMZ July 2014 Bodega Bay

### ISSUE THREAD

**Issue by jbjharvey** [stoqs/stoqs#289]
Hi Mike,

I just met with Erin Satterthwaite and Steven Morgan at Bodega marine lab yesterday and they alerted me to the fact that the last three CTD casts (simz2014c37–39) are not appearing in the stoqs temporal view for that campaign (the last sample visible is (simz2014c36).

They are hoping to get the physical data from these casts to accompany their biological results from the plankton pumping.

Thanks in advance for any assistance you can lend!

Julio

**Comment by MBARIMike** [comment]
Hi Julio,

Let's take this issue off GitHub and ask Erich R. where he has those files stashed on the MBARI network.

-Mike
