### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by zerickso** [stoqs/stoqs#312]
I am having issues installing onto a Mac OS X 10.11.12, using Vagrant 1.8.4 and VirtualBox version 4.3.28 (I have the same issue with the newest version, 5.0.22, but initially thought there might be a back-compatibility problem). Following the instructions, running the curl commands and then 
"sudo vagrant up --provider virtualbox > vagrant_up.log" 
(I used sudo because one of the last statements in the output suggested that might help; the output is identical as best as I can tell if I run without sudo) gave a number of warnings/errors, as well as the output at the end:
"The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong."
The vagrant_up.log file is attached. A few notable warnings/errors are:
==> default: warning: pgdg-centos94-9.4-1.noarch.rpm: Header V4 DSA/SHA1 Signature, key ID 442df0f8: NOKEY

==> default: INFO: Can't locate Tcl/Tk libs and/or headers

==> default: Python build finished, but the necessary bits to build these modules were not found:
==> default: _bsddb             _curses            _curses_panel   
==> default: _tkinter           bsddb185           dbm             
==> default: dl                 gdbm               imageop         
==> default: readline           sunaudiodev                        
==> default: To find the necessary bits, look in setup.py in detect_modules() for the module's name.

==> default: No package rabbitmq-server available.

=> default:  You could try using --skip-broken to work around the problem
==> default: Error: Package: postgis2_94-2.1.8-1.rhel7.x86_64 (pgdg94)
==> default:            Requires: hdf5
==> default: Error: Package: gdal-libs-1.11.0-3.rhel7.x86_64 (pgdg94)
==> default:            Requires: libcfitsio.so.2()(64bit)
==> default: Error: Package: gdal-libs-1.11.0-3.rhel7.x86_64 (pgdg94)
==> default:            Requires: libdapclient.so.6()(64bit)
==> default: Error: Package: gdal-libs-1.11.0-3.rhel7.x86_64 (pgdg94)
==> default:            Requires: libarmadillo.so.4()(64bit)
==> default: Error: Package: gdal-libs-1.11.0-3.rhel7.x86_64 (pgdg94)
==> default:            Requires: libhdf5.so.8()(64bit)
==> default: Error: Package: gdal-libs-1.11.0-3.rhel7.x86_64 (pgdg94)
==> default:            Requires: libfreexl.so.1()(64bit)
==> default: Error: Package: gdal-libs-1.11.0-3.rhel7.x86_64 (pgdg94)
==> default:            Requires: libnetcdf.so.7()(64bit)
==> default: Error: Package: gdal-libs-1.11.0-3.rhel7.x86_64 (pgdg94)
==> default:            Requires: libdapserver.so.7()(64bit)
==> default: Error: Package: gdal-libs-1.11.0-3.rhel7.x86_64 (pgdg94)
==> default:            Requires: libdap.so.17()(64bit)
==> default: Error: Package: gdal-libs-1.11.0-3.rhel7.x86_64 (pgdg94)
==> default:            Requires: libogdi.so.3()(64bit)
==> default: Error: Package: gdal-libs-1.11.0-3.rhel7.x86_64 (pgdg94)
==> default:            Requires: libgta.so.0()(64bit)
==> default: Error: Package: gdal-libs-1.11.0-3.rhel7.x86_64 (pgdg94)
==> default:            Requires: libCharLS.so.1()(64bit)
==> default:  You could try running: rpm -Va --nofiles --nodigest

==> default: Delta RPMs disabled because /usr/bin/applydeltarpm not installed.

and, at the end:

==> default: Need to sudo to install hdf5 packages...
==> default: Loaded plugins: fastestmirror, langpacks
==> default: Loading mirror speeds from cached hostfile
==> default:  * base: mirrors.cmich.edu
==> default:  * extras: mirrors.usc.edu
==> default:  * updates: mirror.supremebytes.com
==> default: No package hdf5 available.
==> default: No package hdf5-devel available.
==> default: Error: Nothing to do
==> default: Exiting /tmp/vagrant-shell

In addition, there were a number of times when a variable in a program was set but not used. ("[-Wunused-but-set-variable]")

The "vagrant ssh -- -X" command works, with the error: 

"/opt/X11/bin/xauth:  file /Users/Zach/.Xauthority does not exist
                                                                Last login: Fri Jun 24 23:53:53 2016 from 10.0.2.2"

However, the "/home/vagrant/" directory only has a Downloads folder (no /dev/), so the "cd ~/dev/stoqsgit && source venv-stoqs/bin/activate" command fails.

Any help appreciated! Thanks.

output from "vagrant up" command included (appended to be a .txt so that GitHub will upload it).

[vagrant_up.log.txt](https://github.com/stoqs/stoqs/files/332793/vagrant_up.log.txt)

**Comment by MBARIMike** [comment]
Thanks for reporting this!

The epel rpm package underwent an upgrade and the older version was no longer available. https://github.com/stoqs/stoqs/pull/313 fixes the problem. Please try again building your STOQS development environment from scratch after getting the modified provision.sh script:

    vagrant destroy
    curl "https://raw.githubusercontent.com/stoqs/stoqs/master/provision.sh" -o provision.sh
    vagrant up --provider virtualbox

Let us know how it goes.

**Comment by zerickso** [comment]
That fix worked great! Thanks for the help.

**Comment by MBARIMike** [comment]
Glad to know it's working for you!
