### ISSUE TITLE
3D Terrain won't render properly. (Google Chrome).

### ISSUE THREAD

**Issue by josephmfaulkner** [stoqs/stoqs#316]
I got a fresh install of the server up and running. It seems to be working properly with the default test data except the 3d terrain isn't displaying properly when I use it on Google Chrome. It seems to display fine when using Firefox. You're using Firefox mainly to test the software, yes? 
![screenshot from 2016-06-29 21 17 59](https://cloud.githubusercontent.com/assets/13591699/16476757/600a2f1a-3e3f-11e6-8ca3-b8e0053f0f35.png)

**Comment by MBARIMike** [comment]
Well that's an interesting artistic rendering of Monterey Bay bathymetry! :-)

I've heard that some Linux WebGL drivers have problems. I suggest visiting http://www.doesmybrowsersupportwebgl.com/ to see what you can learn.

**Comment by josephmfaulkner** [comment]
Okay, so this doesn't seem to be a problem with the software.
