### ISSUE TITLE
Database loading multiple activities from platform even with --append

### ISSUE THREAD

**Issue by duane-edgington** [stoqs/stoqs#361]
I observe that multiple copies of the activity are stored in the database when reloading from a netCDF file that is rewritten with additional data periodically, such as MBARI assets M1 and OA1 (moorings) and nps34 (n34 aka NPS, a glider), using the "--append" option on the load script . This bloats the size of the database, and may have other negative impacts. 
Here is an example, from data loaded into stoqs_canon_september2016 on mbari server kraken, for data from asset n34

$ stoqs/manage.py shell_plus --settings=config.settings.local 
acts = Activity.objects.using('stoqs_canon_september2016').filter(name__contains='NPS')

In [4]: acts
Out[4]: [Activity: OS_Glider_NPS_G34_20160720_TS.nc starting at 2016-07-11 00:00:00 , Activity: OS_Glider_NPS_G34_20160720_TS.nc starting at 2016-07-11 00:00:00 , Activity: OS_Glider_NPS_G34_20160720_TS.nc starting at 2016-07-11 00:00:00 , Activity: OS_Glider_NPS_G34_20160720_TS.nc starting at 2016-07-11 00:00:00 , Activity: OS_Glider_NPS_G34_20160720_TS.nc starting at 2016-07-11 00:00:00 , Activity: OS_Glider_NPS_G34_20160720_TS.nc starting at 2016-07-11 00:00:00 , Activity: OS_Glider_NPS_G34_20160720_TS.nc starting at 2016-07-11 00:00:00 , Activity: OS_Glider_NPS_G34_20160720_TS.nc starting at 2016-07-11 00:00:00 , Activity: OS_Glider_NPS_G34_20160720_TS.nc starting at 2016-07-11 00:00:00 , Activity: OS_Glider_NPS_G34_20160720_TS.nc starting at 2016-07-11 00:00:00 , Activity: OS_Glider_NPS_G34_20160720_TS.nc starting at 2016-07-11 00:00:00 ]

The only way I know to rectify this is by deleting all the activities from the database, and then reloading the activity. This is tedious if the activities are to be loaded on a campaign tempo (say hourly or daily).

**Comment by MBARIMike** [comment]
I'm testing some fixes for this issue now.

**Comment by MBARIMike** [comment]
I suspect that [this code](https://github.com/stoqs/stoqs/blob/285247a1bec096fb6e7bb751fd3e343c32e33e1a/stoqs/loaders/__init__.py#L527-L531) is the culprit. As new self.endDatetimes are generated new Activities are being created.

**Comment by MBARIMike** [comment]
There were a few problems:

1. The `load_NPS34()` method was missing the code that finds the last record in the database
2. https://github.com/stoqs/stoqs/pull/315 broke lookup by `aName`
3. The `createActivity()` method was creating new activities with new enddates

https://github.com/stoqs/stoqs/pull/362 should fix them.

**Comment by stoqs** [comment]
https://github.com/stoqs/stoqs/pull/375 is a more rigorous fix. Please report if multiple Activities are still being created.

**Comment by MBARIMike** [comment]
Is this Issue still a problem?

**Comment by duane-edgington** [comment]
I think this is no longer a problem.

Duane
