### ISSUE TITLE
Explore using Django --liveserver option for functional tests

### ISSUE THREAD

**Issue by MBARIMike** [stoqs/stoqs#417]
I came across this in the Django documentation:

https://docs.djangoproject.com/en/1.8/topics/testing/tools/#liveservertestcase

The [current functional tests](https://github.com/stoqs/stoqs/blob/973c49f0aa0fc2b4b258c99b760444ece65eb038/test.sh#L66-L76) are done with the `runserver` command; the `--liveserver` option may be a better way to do this.

**Comment by MBARIMike** [comment]
It seems that using `StaticLiveServerTestCase` and `--liveserver` are required for getting accurate coverage reports. Testing of [this code](https://github.com/stoqs/stoqs/blob/63d306761f6820d61dce7e49d44fdcfa19c37673/test.sh#L66-L76) reveals that killing the server (even with the TERM signal) prevents coverage from writing its data to .coverage.

**Comment by stoqs** [comment]
Fixed in python3 branch with https://github.com/stoqs/stoqs/pull/541
