### ISSUE TITLE
Upgrade Django

### ISSUE THREAD

**Issue by GoogleCodeExporter** [stoqs/stoqs#44]
```
What steps will reproduce the problem?
1. Visit the django documentation page for version 1.3: 
https://docs.djangoproject.com/en/1.3/contents/
2. Observe the warning at the top of the page: This document is for an insecure 
version of Django that is no longer supported. Please upgrade to a newer 
release!

Minor version upgrades require reading the release notes for each version. 
Initial perusal indicates that some source code and configuration changes will 
be required. The upgrade can be implemented on a branch of the Mercurial 
repository and then merged with the main trunk. 


```

Original issue reported on code.google.com by `MBARIm...@gmail.com` on 28 Feb 2014 at 10:37

**Comment by MBARIMike** [comment]
The goal of the django17upgrade branch is to have a simple software upgrade that does not require rebuilding any of the legacy production databases. The production databases have been built with PostGIS 1.5 on PostgreSQL 9.1; therefore, this branch should hold off on upgrading to PostGIS 2.x

See: https://docs.djangoproject.com/en/1.7/ref/contrib/gis/install/postgis/

There are good reasons to upgrade to PostGIS 2.x. Discovering the software dependencies will be one of the outcomes of this issue.

**Comment by MBARIMike** [comment]
Thanks to @Jergutierrez who is working on Issue #57 for helping to discover the PostGIS2 issue.

**Comment by MBARIMike** [comment]
After installing PostGIS 2.0 I renamed the databases in PostgreSQL (so that 1.5 can also be installed):

stoqs=# alter database template_postgis rename to template_postgis20;
ALTER DATABASE
stoqs=# alter database postgis rename to postgis20;
ALTER DATABASE

**Comment by MBARIMike** [comment]
Postgres 9.3 requires PostGIS 2.x. See: https://trac.osgeo.org/postgis/wiki/UsersWikiPostgreSQLPostGIS.

This means that merging the django17upgrade branch will require new stoqs databases built using the new PostGIS 2.x template. A postgresql-9.3 server can be set up in parallel to the legacy server on production systems. The webapp location can be switched over once all of the legacy databases have been reloaded with the new template.

**Comment by MBARIMike** [comment]
Installing GDAL in virtualenv is not straight forward. See:

http://tylerickson.blogspot.com/2011/09/installing-gdal-in-python-virtual.html

pypi's latest version is 1.11.2, but yum installs 1.9.2. 

Doing:

export LD_PRELOAD=/usr/lib64/libgdal.so.1
pip install gdal==1.9.1

seemed to work, but the libraries installed are 1.9.2:

$ gdal-config --version
1.9.2

'pip install gdal==1.9.2' returns this:

$ pip install gdal==1.9.2
Collecting gdal==1.9.2
  Could not find a version that satisfies the requirement gdal==1.9.2 (from versions: 1.5.0, 1.5.2, 1.6.0, 1.6.1, 1.7.0, 1.7.1, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.11.0, 1.11.1, 1.11.2)
  No distributions matching the version for gdal==1.9.2

Arrrggghhh!

**Comment by MBARIMike** [comment]
Some progress achieved. See commit https://github.com/MBARIMike/stoqs/commit/5ad0e68aeb6cc6ec720c8608bc1715e361216a41 and the 3 more following. Am now able to execute the stoqs/manage.py for Django 1.7, at least for the syncdb command.

**Comment by MBARIMike** [comment]
Significant milestone reached: 
- Continuous Integration implemented through Travis-ci
- Test coverage reported through coveralls.io
- Requirements checked by Requires.io

Badges in the README.md file report on the status of the above items. Build and coverage tests are now triggered with each Pull Request. When the PR is merged the badges get updated.

The instructions at https://github.com/stoqs/stoqs/tree/django17upgrade have been tested on Windows, Mac, and Linux computers. The installation takes about an hour depending on network speed and host computer performance; it takes up about 5 GB of disk space.

**Comment by MBARIMike** [comment]
Another significant milestone reached: The django17upgrade branch is now running with Django-1.8! 

The major remaining task is to document and test the new method (with django-environ) for specifying multiple database/campaigns. The privateSettings file is being replaced with the setting of environment variables so that http://12factor.net/ guidelines are followed.

**Comment by stoqs** [comment]
PR #154 closes this issue!
