### ISSUE TITLE
Unable to generate netCDF files for recent profiling CTD datafiles

### ISSUE THREAD

**Issue by duane-edgington** [stoqs/stoqs#841]
Using code current Feb 7 2019, in docker image built on my mac system using instructions from issue #836, I am unable to generate netCDF files from pctd data files stored in location smb://atlas/ODSS/data/other/routine/Platforms/Ships/WesternFlyer/pctd/cn18  

The datafiles appear on inspection to be properly formated, at near as I can tell.

The command used to generate the netCDF files is
docker-compose exec stoqs stoqs/loaders/CANON/toNetCDF/pctdToNetcdf.py -i $LOCALDIR -t "Profile CTD data from R/V Western Flyer during CANON - September 2018"

This command and the associated script that sets up the $LOCALDIR variable was able to successfully generate netCDF files from previous (2017) datafiles 

No error messages, warnings, or any other output was generated by the pctdToNetcdf.py program for these datafiles.

**Comment by MBARIMike** [comment]
Looks like there were some Python 3 issues that didn't get resolved for the `pctdToNetcdf.py`. The error reporting can also be better. Lastly, mapping to the volume mount inside the Docker container needs to be dealt with.

**Comment by MBARIMike** [comment]
I suspect we might have similar problems with `uctdToNetcdf.py`...

**Comment by duane-edgington** [comment]
Probably, but I did not try that yet. I believe the profiling CTDs are more urgent to the CANON team than the underway CTD, but maybe not.

Duane

**Comment by MBARIMike** [comment]
I just merged changes to fix `pctdToNetcdf.py`. Please pull and try it out. I'll start looking at `uctdToNetcdf.py`.

**Comment by MBARIMike** [comment]
The shell scripts `makeWFpctdNetCDF.sh` and `makeWFuctdNetCDF.sh` should be used for processing data from different campaigns. They now accept an optional 'docker' argument for execution on a Docker-based system.

**Comment by duane-edgington** [comment]
When I used the new script with the docker option I got this error message:

...
odssadm@odss.mbari.org's password: 
/srv/docker/cn18/*.nc: No such file or directory
rm: /srv/docker/cn18: No such file or directory

**Comment by MBARIMike** [comment]
Ah, yes...

It looks like the Docker LOCALDIR is being to used to scp the .nc files back to the server. PR coming up.

**Comment by MBARIMike** [comment]
Note that the `--pattern` option can be passed to `pctdToNetcdf.py` and `uctdToNetcdf.py` to specify which files to process in a crowded directory.  It's likely easier to leave the "routine" Seabird data files in place on the server in the `/data/other/routine/Platforms/Ships/WesternFlyer/[pu]ctd` directories and use the `--pattern` option. I'll add an example of doing that to the last PR.

**Comment by MBARIMike** [comment]
O.K. https://github.com/stoqs/stoqs/pull/844 has been merged. I suggest that when it comes time to process pctd and uctd files from other ships that we generalize `makeWFpctdNetCDF.sh` and `makeWFuctdNetCDF.sh` to `make_pctdNetCDF.sh` and `make_uctdNetCDF.sh` and adjust variable settings (commenting out historical ones) as needed.

**Comment by MBARIMike** [comment]
Can we close this Issue?

**Comment by duane-edgington** [comment]
resolved. Thanks Mike.

**Comment by duane-edgington** [comment]
Done

duane
